Vaious optimizations and fixes
austind/get_l3_facts pull request #1
Opened 2019-10-25 14:42 UTC by markhayes0338

Broke out argparse to its own function
Added ability to use text file with list of devices to gather l3 facts
A few other fixes

2019-10-29 21:40 UTC, austind requested changes
Looks good overall. See corrections. Thanks for contributing!

2019-10-29 21:40 UTC, austind commented on get_l3_facts.py
> +    )
Change option name to `--input` / `-i`

2019-10-29 21:40 UTC, austind commented on get_l3_facts.py
> +    sys.exit(main(sys.argv))
What does this give us?

2019-10-29 21:40 UTC, austind commented on get_l3_facts.py
> +import os
Alphabetize imports

2019-10-29 21:40 UTC, austind commented on get_l3_facts.py
> +def main(argv):
No need to pass `argv`, `argparse` handles this.

2019-10-29 21:40 UTC, austind commented on get_l3_facts.py
> +def get_args(args):
No need to take `args`, `argparse` handles it -- see comments below

2019-10-29 21:40 UTC, austind commented on get_l3_facts.py
> +    args = get_args(argv[1:])
After removing `args` from `get_args()` and `main()`, call this as `get_args()`

2019-10-29 22:12 UTC, markh0338 commented
requested updates have been committed.

2019-10-29 23:31 UTC, austind commented
Alphabetize imports still pending

2019-10-30 01:09 UTC, markh0338 commented
Missed that. Reordered and separated 3rd party from standard libraries

2019-10-30 21:00 UTC, merged